# Generated by Django 4.0 on 2021-12-23 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('thumbnail_url', models.CharField(max_length=254)),
                ('youtube_url', models.CharField(max_length=254)),
                ('data_caption', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
            ],
        ),
    ]
