# Generated by Django 4.0 on 2022-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_release_blurb_alter_release_title'),
        ('videos', '0004_video_youtube_id_alter_video_data_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='artist',
        ),
        migrations.AddField(
            model_name='video',
            name='artists',
            field=models.ManyToManyField(to='homepage.Artist'),
        ),
    ]
