# Generated by Django 4.0 on 2021-12-21 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('artist', models.CharField(max_length=254)),
                ('artist2', models.CharField(max_length=254)),
                ('artist3', models.CharField(max_length=254)),
                ('producer', models.CharField(max_length=254)),
                ('recorded_by', models.CharField(max_length=254)),
                ('youtube_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('bandcamp_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
