# Generated by Django 4.0 on 2021-12-23 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.CharField(max_length=254)),
            ],
        ),
    ]
