# Generated by Django 4.0 on 2022-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_event_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventbrite_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
