# Generated by Django 4.0 on 2022-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_rename_instgram_url_artist_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='blurb',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
