# Generated by Django 4.0 on 2022-04-13 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_release_blurb_alter_release_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('active', models.BooleanField(default=True)),
                ('carousel_active', models.BooleanField(default=True)),
                ('artists', models.ManyToManyField(to='homepage.Artist')),
            ],
        ),
    ]
