# Generated by Django 4.0 on 2022-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery_active',
            field=models.BooleanField(default=True),
        ),
    ]
