# Generated by Django 4.0 on 2022-04-05 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_release_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('youtube_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('bandcamp_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='release',
            name='artist2',
        ),
        migrations.RemoveField(
            model_name='release',
            name='artist3',
        ),
        migrations.RemoveField(
            model_name='release',
            name='producer',
        ),
        migrations.AddField(
            model_name='release',
            name='carousel_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('venue', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('artists', models.ManyToManyField(to='homepage.Artist')),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.artist'),
        ),
    ]
