# Generated by Django 4.0 on 2022-04-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_artist_remove_release_artist2_remove_release_artist3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.artist'),
        ),
    ]
