# Generated by Django 4.0 on 2022-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_artist_bio_alter_release_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instgram_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
