# Generated by Django 4.0 on 2022-04-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_event_eventbrite_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='instgram_url',
            new_name='instagram_url',
        ),
    ]
