# Generated by Django 4.0 on 2022-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_video_artist_video_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
