# Generated by Django 4.0 on 2022-04-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organic',
        ),
    ]
